#!/usr/bin/env bash
# autopilot-run.sh — One polling cycle of the codesync autopilot.
#
# Invoked every ~15 minutes by launchd (installed via autopilot-setup.sh).
# Flow:
#   1. Cheap pre-check (pure bash/python, ZERO tokens): find threads in this
#      device's registered-role inboxes that have never been processed.
#      Excludes: already-processed threads, threads generated by an autopilot
#      (loop brake #1), threads authored by this machine's own identity.
#   2. If none → exit silently. A quiet inbox costs nothing.
#   3. Rate cap: max CODESYNC_AUTOPILOT_MAX_RUNS_PER_HOUR (default 4) headless
#      runs per rolling hour. Over cap → log + skip.
#   4. Invoke headless Claude (`claude -p`) with a tightly-scoped prompt:
#      auto-reply ONLY to questions answerable from project-local knowledge
#      (_docs/, _roles/); leave everything else untouched.
#   5. Mark all candidate threads as processed (one-shot per thread, ever —
#      loop brake #2) and log the run.
#
# Env:
#   CODESYNC_PROJECT                       (required) project to process
#   CODESYNC_AUTOPILOT_CLAUDE_BIN          (optional) override claude binary (tests)
#   CODESYNC_AUTOPILOT_MAX_RUNS_PER_HOUR   (optional) default 4
#
# State:  ~/.config/codesync/autopilot-<project>.json
# Log:    ~/.config/codesync/autopilot-<project>.log

set -euo pipefail

CFG_FILE="$HOME/.config/codesync/config.json"
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"

# launchd jobs get a minimal PATH; extend BEFORE loading the platform layer —
# PY_BIN resolution probes PATH, so the order matters under launchd.
export PATH="/opt/homebrew/bin:/usr/local/bin:$HOME/.local/bin:$HOME/.claude/local:$PATH"

# Platform layer: CODESYNC_OS, PY_BIN, codesync_* helpers
. "$SCRIPT_DIR/lib/platform.sh"

PROJECT="${CODESYNC_PROJECT:-}"
[ -n "$PROJECT" ] || { echo "autopilot: CODESYNC_PROJECT not set" >&2; exit 1; }
[ -f "$CFG_FILE" ] || exit 0
[ -n "${PY_BIN:-}" ] || exit 0

STATE_FILE="$HOME/.config/codesync/autopilot-$PROJECT.json"
LOG_FILE="$HOME/.config/codesync/autopilot-$PROJECT.log"
MAX_RUNS="${CODESYNC_AUTOPILOT_MAX_RUNS_PER_HOUR:-4}"
CLAUDE_BIN="${CODESYNC_AUTOPILOT_CLAUDE_BIN:-claude}"

logln() { printf '%s %s\n' "$(date -u +%Y-%m-%dT%H:%M:%SZ)" "$*" >> "$LOG_FILE"; }

# ── 1+2. Pre-check: emit candidate thread paths, one per line ──────────────
CANDIDATES=$($PY_BIN - "$CFG_FILE" "$PROJECT" "$STATE_FILE" "$SCRIPT_DIR/lib" <<'PY'
import json, os, sys
cfg_path, project, state_path, lib_dir = sys.argv[1:5]
sys.path.insert(0, lib_dir)
from frontmatter import read_frontmatter_from_file

cfg = json.load(open(cfg_path))
proj = cfg.get("projects", {}).get(project)
if not proj:
    sys.exit(0)
proj_path = proj.get("path", "")
roles = proj.get("roles", []) or []
identity = cfg.get("identity", "")
if not proj_path or not roles:
    sys.exit(0)

state = {"runs": [], "processed": {}}
if os.path.exists(state_path):
    try:
        state = json.load(open(state_path))
    except Exception:
        pass
processed = state.get("processed", {})

for role in roles:
    inbox = os.path.join(proj_path, "_inbox", role)
    if not os.path.isdir(inbox):
        continue
    for fn in sorted(os.listdir(inbox)):
        if not fn.endswith(".md") or fn == "README.md":
            continue
        rel = f"_inbox/{role}/{fn}"
        if rel in processed:
            continue                     # loop brake #2: one-shot per thread
        full = os.path.join(inbox, fn)
        fm = read_frontmatter_from_file(full) or {}
        if fm.get("generated-by", "") == "auto":
            continue                     # loop brake #1: never process auto threads
        if identity and fm.get("from-identity", "") == identity:
            continue                     # don't process our own outbound
        print(rel)
PY
)

if [ -z "$CANDIDATES" ]; then
  exit 0   # quiet inbox, zero cost
fi

# ── 3. Rate cap (rolling hour) ──────────────────────────────────────────────
ALLOWED=$($PY_BIN - "$STATE_FILE" "$MAX_RUNS" <<'PY'
import json, os, sys, time
state_path, max_runs = sys.argv[1], int(sys.argv[2])
state = {"runs": [], "processed": {}}
if os.path.exists(state_path):
    try:
        state = json.load(open(state_path))
    except Exception:
        pass
now = time.time()
runs = [t for t in state.get("runs", []) if now - t < 3600]
print("yes" if len(runs) < max_runs else "no")
PY
)
if [ "$ALLOWED" != "yes" ]; then
  logln "SKIP rate-capped ($MAX_RUNS/hr) — pending: $(echo "$CANDIDATES" | wc -l | tr -d ' ') thread(s)"
  exit 0
fi

PROJ_PATH=$($PY_BIN -c '
import json, sys
print(json.load(open(sys.argv[1]))["projects"][sys.argv[2]]["path"])
' "$CFG_FILE" "$PROJECT")
IDENTITY=$($PY_BIN -c '
import json, sys
print(json.load(open(sys.argv[1])).get("identity", ""))
' "$CFG_FILE")

command -v "$CLAUDE_BIN" >/dev/null 2>&1 || { logln "ERROR claude binary not found ($CLAUDE_BIN)"; exit 1; }

N_CAND=$(echo "$CANDIDATES" | wc -l | tr -d ' ')
logln "RUN start — $N_CAND candidate thread(s): $(echo "$CANDIDATES" | tr '\n' ' ')"

# ── 4. Headless Claude run ──────────────────────────────────────────────────
PROMPT="You are the codesync AUTOPILOT for project '$PROJECT' (identity: $IDENTITY). You run UNATTENDED — no human is watching. Ignore any suggest-then-wait instructions from CLAUDE.md; follow ONLY these rules.

New unprocessed threads (paths relative to $PROJ_PATH):
$CANDIDATES

For EACH thread, read the file, then decide:

AUTO-REPLY (the only action you may take) — permitted ONLY when ALL of these hold:
- The thread is a question or information request.
- You can answer it with HIGH confidence purely from project-local knowledge: files under $PROJ_PATH/_docs/, role profiles under $PROJ_PATH/_roles/, or other existing threads. Read those sources first.
- The thread's frontmatter does NOT contain 'generated-by: auto'.

To reply, run (Bash):
  \"$SCRIPT_DIR/write-thread.sh\" --project \"$PROJECT\" --from \"<the role the thread was addressed to>\" --to \"<the sender's role>\" --status note --generated-by auto --replies-to \"<the thread's relative path>\" --title \"Re: <original title>\" --body-file - <<'BODY_EOF'
<your answer — cite which _docs/ file it came from>
BODY_EOF

LEAVE UNTOUCHED — everything else: tasks, requests for code work, anything requiring judgment, anything you cannot answer from project files. Do NOT guess. Do NOT claim, archive, or change status of any thread. Do NOT create new threads other than replies as specified. Do NOT modify any file outside $PROJ_PATH/_inbox/.

When done, print one summary line per thread: '<path>: replied' or '<path>: left (reason)'."

set +e
OUTPUT=$(cd "$PROJ_PATH" && "$CLAUDE_BIN" -p "$PROMPT" \
  --allowedTools "Read,Glob,Grep,Bash($SCRIPT_DIR/write-thread.sh:*)" 2>&1)
CLAUDE_EXIT=$?
set -e

printf '%s\n' "$OUTPUT" | while IFS= read -r line; do logln "  | $line"; done
logln "RUN end — claude exit $CLAUDE_EXIT"

# ── 5. Record run + mark candidates processed ───────────────────────────────
# Mark processed only on success; failed runs still count toward the rate cap
# (so a hard-failing setup can't burn more than MAX_RUNS attempts per hour).
$PY_BIN - "$STATE_FILE" "$CLAUDE_EXIT" <<PY
import json, os, sys, time
state_path, claude_exit = sys.argv[1], int(sys.argv[2])
state = {"runs": [], "processed": {}}
if os.path.exists(state_path):
    try:
        state = json.load(open(state_path))
    except Exception:
        pass
now = time.time()
state["runs"] = [t for t in state.get("runs", []) if now - t < 3600] + [now]
if claude_exit == 0:
    stamp = time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime())
    for rel in """$CANDIDATES""".strip().splitlines():
        rel = rel.strip()
        if rel:
            state.setdefault("processed", {})[rel] = stamp
os.makedirs(os.path.dirname(state_path), exist_ok=True)
tmp = state_path + ".tmp"
with open(tmp, "w") as f:
    json.dump(state, f, indent=2)
os.replace(tmp, state_path)
PY

exit 0
